### ISSUE TITLE
Generate binaries for windows

### ISSUE THREAD

**Issue by cburgdorf** [thoughtram/clog#12]
@Ryman do you have any experience with Rust on windows? Especially how to automate it? Does it make sense to put windows on a vagrant box and somehow script it to auto generate windows builds?

**Comment by kbknapp** [comment]
I tested this out today, but it fails to build because of dep `time`. I haven't looked into it too deeply, but it looks like `time` is using a custom build script which isn't compatible with Windows.

**Comment by kbknapp** [comment]
I just uploaded a windows binary to 

http://wod.twentyfives.net/bin/clog/clog-v0.7.0_windows-x64.zip

**Comment by PascalPrecht** [comment]
What's the status of this?

**Comment by kbknapp** [comment]
We have a working windows binary of 0.7.0
