### ISSUE TITLE
Implement aliases

### ISSUE THREAD

**Issue by cburgdorf** [thoughtram/clog#3]
`ft(x)` should expand to `feat(x)`
`fx(x)` should expand to `fix(x)`
`rf(x)` should expand to `refactor(x)`
`ch(x)` should expand to `chore(x)`

**Comment by kbknapp** [comment]
Since I'm less familiar with the conventional changelog, are these standard aliases? If not, perhaps this is something that would go well with #20? Where a user could specify their own aliases.

**Comment by kbknapp** [comment]
#27 is a bigger one, see the commit message of 44f7d49 for details, should be a good change and very easy to add more aliases from now on ;)

**Comment by vyp** [comment]
> Since I'm less familiar with the conventional changelog, are these standard aliases?

No I do not think so, but I may be wrong. And yes, I think that's a great reason to have a .clog file.
