### ISSUE TITLE
Add ability to specify changlog file name

### ISSUE THREAD

**Issue by orclev** [thoughtram/clog#34]
It would be nice if there was both a command line option, and a config file parameter to specify the name of the changelog file. In particular it seems it's very common to call the file "CHANGELOG.md", where as the filename in clog is hard coded currently to "changelog.md".

**Comment by kbknapp** [comment]
This should be an easy addition. I'll wait for @cburgdorf to give some guidance on how he'd like this implemented. I see these options as possibilities:

**Option 1**
* Use `changelog.md` in the absence of any command line options or `.clog.toml` field
* Use a command line option or `.clog.toml` field to specify a new file

**Option 2**
* Use `changelog.md` in the absence of any command line options or `.clog.toml` field
* Use a command line option to specify `stdout` as the output (which would allos `clog > CHANGELOG.md`

**Option 2**
* Use `stdout` as the default for no `.clog.toml` field
* Use a `.clog.toml` field to specify a default name

I'd lean towards Option 1.

**Comment by cburgdorf** [comment]
Yep, I'm also in favor of the first option.
Am 04.05.2015 23:31 schrieb "Kevin K." <notifications@github.com>:

**Comment by kbknapp** [comment]
#35 adds this

**Comment by orclev** [comment]
Awesome, great turn around, thanks.
