### ISSUE TITLE
Add support for Stash as a repository

### ISSUE THREAD

**Issue by orclev** [thoughtram/clog#38]
Stash and github are largely compatible but differ in very slight ways. It would be nice if clog could generate links not only for github, but also for stash. In order to support this there should be an option to provide the flavor of repository links should be generated for.

I've implemented this in a fork and can do a pull request assuming you don't have any changes you want me to implement. My current implementation adds a new CLI parameter `--repoflavor` and a TOML option `repo-flavor`, both of which accept either "github" or "stash" as arguments (case insensitive). This new parameter controls two aspects of the changelog generation. Firstly it changes the commit links to follow the proper convention for the respective repository flavor. Secondly it changes the issue links to not be generated in the case of stash (because it doesn't have built in issue tracking). This approach is flexible and it should be relatively trivial to add support for other kinds of repository flavor down the line (bitbucket maybe?).

**Comment by kbknapp** [comment]
Go ahead and put the PR in, and if needed we can make changes from there. Ultimately @cburgdorf would make the call, but I think this would be a good addition making `clog` even more versatile.
