### ISSUE TITLE
Split clog into lib and bin

### ISSUE THREAD

**Issue by cburgdorf** [thoughtram/clog#44]
It's currently a bit unfortunate that clog's core functionality isn't available as a lib. If I want to write another app that wants to use clog I would have to find a way to bundle the binary with my app and call it as another process. But that doesn't seem to be easily supported by cargo yet.

//cc @kbknapp

**Comment by cburgdorf** [comment]
Maybe we could just split it into lib and bin but keep it in one repository like mentioned [here](http://stackoverflow.com/questions/26946646/rust-package-with-both-a-library-and-a-binary/26953326#26953326)

**Comment by kbknapp** [comment]
I think this is a really great idea and should be easy to do. I'm in
vacation this week, and have limited access to computers but I can split
them out pretty easy once I get back in a few days. And I like the idea of
keeping them in one repo.

The splitting should be super straight forward, the docs may take a day or
two to write but I think good docs are a must.

**Comment by kbknapp** [comment]
I'm back home now and will begin putting this together. I'll put in a PR soon to discuss how it turns out.

**Comment by kbknapp** [comment]
#45 is in - Docs need to be written, and there are areas that could be refined and re-arranged but it works  :)

**Comment by kbknapp** [comment]
Closed with #45
