### ISSUE TITLE
Add instructions on how to install the binaries

### ISSUE THREAD

**Issue by PascalPrecht** [thoughtram/clog#47]
Love the work that is happening here.

However, whereas the readme describes how I can use `clog` as a library, there's no information on how I can install and use the binaries. I know, it might be obvious to a lot of people, but to make it even easier for everyone, It'd be nice if there was a n instruction that tells you where to download the binary, where to put it on your system and finally, that you might have to configure your $PATH and how.

**Comment by cburgdorf** [comment]
I was wondering that for myself recently and I guess it depends on the actual operating system and personal preference but I ended up putting those binaries into `$Home/bin`. You can read up more about that [here](http://unix.stackexchange.com/questions/36871/where-should-a-local-executable-be-placed). That said, clog is already available through some package managers for linux distribution. I have no idea where those package managers install the programs.

**Comment by vyp** [comment]
Because clog is a self contained binary (the application), installation is as simple as putting it in the path.

**Comment by PascalPrecht** [comment]
Right, I get that. And I'd like to see exactly that in the installation instructions :)

I'm sure this will help a ton of people that would like to try out the tool but aren't familiar with how the $PATH works etc.

**Comment by vyp** [comment]
Right yep sorry, was just clarifying.

**Comment by vyp** [comment]
@kbknapp Did cargo ever get the `install` command? And are you sure you want to link to your binaries? Because another option would be to upload to the github releases pages, therefore not affecting your bandwidth.

**Comment by kbknapp** [comment]
Not yet, according to the [Rust subteams report](https://internals.rust-lang.org/t/subteam-reports-2015-07-01/2321) they are working on it though.

I don't mind link the binaries for now, they're super small and I've got 1TB a month, so I think we're good for now. In fact I just uploaded the new 0.8.2 binary (linux only so far, I haven't compiled on OS X or Windows yet, I'll probably do that tomorrow if a get a second), as well as a `clog-bin` for the Arch AUR.

**Comment by vyp** [comment]
Nice installation instructions! Is there a homebrew recipe? Also, remember to put clog-bin to aur4, there's only a couple of days left!

**Comment by PascalPrecht** [comment]
I <3 this! Thank you @kbknapp and keep up the good work :)

**Comment by kbknapp** [comment]
@vyp There isn't a homebrew recipe out yet...I'm not super familiar with Macs or `brew` so if someone  that is wants to head that up using the binaries I posted feel free!
