### ISSUE TITLE
docs: add info about commitizen

### ISSUE THREAD

**Issue by PascalPrecht** [thoughtram/clog#49]
A nice project that popped recently in my twitter timeline. It's a CLI tool that helps you writing commit messages that follow conventions. I think it'd be nice to add it to the readme as companion tool.

Here's a link: http://commitizen.github.io/cz-cli/

**Comment by kbknapp** [comment]
That's a neat project! I wonder how difficult it would be to bundle that functionality with `clog` being that users can supply their own sections as well (which `git-cz` wouldn't support)?

**Comment by PascalPrecht** [comment]
With sections you mean custom conventions?

**Comment by kbknapp** [comment]
Yes. So ultimately, it'd be awesome to incorporate something like `commitzen` which reads the `.clog.toml` (if any) and gives the user a selection of not just the default conventions, but also any custom ones they specified as well.

But I think just including `commitzen` as nice companion project in the mean time is good too :)

**Comment by orclev** [comment]
It's interesting, but I don't like some things about it. In particular it adopts what I feel is a anti-pattern from the javascript world of installing shared dependencies in the same folder as your project (I.E. the node_modules folder). With clog I can just copy the binary and use that wherever, but with commitizen I need to install node and either check its dependencies into my projects, or else include an extra development install step of using npm to install the commitizen depencies.

I think it's worth mentioning the project, but I wouldn't do more than that at this point.

**Comment by vyp** [comment]
@orclev I dislike the npm package manager too, but commitizen should be installed globally, thus not cluttering up your project.

In any case, I agree though and think that any commitizen integration should be an optional bonus for those who want it.

**Comment by PascalPrecht** [comment]
Let's just stick with added a note about the project to clog's readme
