### ISSUE TITLE
fix(log_writer): generate list for component even for one commit

### ISSUE THREAD

**Issue by PascalPrecht** [thoughtram/clog#54]
I encountered a behaviour which I consider a bug, but I might be wrong. This is my commit history:

```sh
* 2970d06 (HEAD, tag: 1.1, master) fix(lexer): tokenize more strict
* 083c40b (tag: 1.0) fix(compiler): adds missing constructor parameter
* ecc200d fix(compiler): adds missing constructor
* c5c2471 feat(compiler): implements lexer
* 6603503 chore: initial commit
```

As we can see, there's only one commit for `lexer`. Generating a changelog, gives me this output:

![screen shot 2015-07-13 at 14 51 20](https://cloud.githubusercontent.com/assets/445106/8649904/a26053b2-296e-11e5-86c3-e39c35dee38b.png)

Component `lexer` doesn't have a list. IMO even if there's only a single message for a component, a list should be generated.

**Comment by kbknapp** [comment]
Has this been officially decided on? It's an easy change if we want to add it before a new release gets cut after #64 is merged

**Comment by PascalPrecht** [comment]
I'd like to see this land, but @cburgdorf should also leave his opinion on that.

**Comment by cburgdorf** [comment]
The way we currently handle that is the same way as in the conventional changelog project that is used for Angular. See here: https://github.com/angular/angular.js/blob/master/CHANGELOG.md

Well, except for the colon (`:`) that @kbknapp mentioned. I guess we should just add the colon but keep the rest as is.

**Comment by PascalPrecht** [comment]
You're the boss. Okay, then once this colon fix landed we can close this issue.
