### ISSUE TITLE
ui/ux(cli): create and update message

### ISSUE THREAD

**Issue by PascalPrecht** [thoughtram/clog#55]
This is really just for better UX:

Whenever I **create** or update a changelog with `clog` the output I get is always:

```
$ changelog updated (took xx ms)
```

I  think it'd be nicer if the tools states that it **created** a changelog, if that's the case and only **updates** if **that's** the case.

**Comment by kbknapp** [comment]
This is an easy fix, but with #58 I don't know if they're compatible. For example, if I do

```
$ clog > some_file.md
```
I may not want that file to contain "Updated/Created 15ms" ( now if we don't implement #58 this is a moot point and very simple to fix :P )

**Comment by PascalPrecht** [comment]
@kbknapp you're totally right. Does it make sense to generate that output only if a writer is applied? Not sure what's the standard way in UNIX commands to handle this..

**Comment by kbknapp** [comment]
@PascalPrecht Yes, that's good idea, only write this message when **not** writing to `stdout`.

**Comment by PascalPrecht** [comment]
@kbknapp I'd like to keep as UNIX-y as possible. If that's how all UNIX commands handle these cases, I'm voting for that.
