### ISSUE TITLE
chore: create 1.0 Milestone

### ISSUE THREAD

**Issue by kbknapp** [thoughtram/clog#61]
It'd be nice to have a 1.0 milestone and mark particular issues against that milestone to be able to track progress. I'd set this up, but I'm not sure which issues @cburgdorf and @PascalPrecht want to be 1.0 priorities/blockers.

I'd suggest:  #52 #53 #55 #56 #58 #60 and #62

**Comment by PascalPrecht** [comment]
Perfect, I think this is a good list for 1.0. Let's make this happen :)

@kbknapp do you want to set up the milestone?

**Comment by cburgdorf** [comment]
I did it. Closing here. Feel free to reopen if that needs further discussion.

**Comment by kbknapp** [comment]
Looks good!
