### ISSUE TITLE
Should clog allow reading old changelog without writing to it?

### ISSUE THREAD

**Issue by kbknapp** [thoughtram/clog#63]
With the new #64 PR I realized that `clog` cannot currently read an old changelog and save to a new location. **If** it reads from an old changelog, it *always* writes back out to that location. It may be useful to allow reading from an old changelog and outputting to a new one, or arbitrary location.

Imagine wanting to run `clog` and suck up all the old data, but output to `stdout`? Currently you can't. It either reads everything from the old one, and writes back out to it, or doesn't read the old one and prints to `stdout`.

What do you think?

**Comment by cburgdorf** [comment]
I agree that it would be nice to support this scenario.

**Comment by vyp** [comment]
Yes definitely, I don't see any downsides to this, did you think of any? Does it have breaking changes?

**Comment by kbknapp** [comment]
@vyp Writing to stdout alone as a default is a breaking change. But being that we're almost at a state of 1.0 it shouldn't be a huge issue.

I agree this should be done...but the question is *how*?

Currently, we accept either a `-o <file>` or `out-file` field in the `.clog.toml` which sets the *output*, but we don't currently have a way to set *input only*, i.e. "read from file, but output elsewhere."

We have a few possibilities for another option/TOML field: `--in-file`, `--old`, `--previous`, `--changelog`, etc. So any thoughts on a name?

Would it be confusing for a user to have an `--out-file` and `--in-file`? 

My proposal:

 * Add `--in-file <file>` (and TOML field), *and* `--changelog <file>` (with TOML field) in addition to the already existing `--out-file <file>` (and TOML field).
 * This allows user to specify *only* an out file if they want one, or *only* an input file. If they want it to be used as both, we have `--changelog`
 * This is a non-breaking change because `--out-file` remains unchanged.

Thoughts?

**Comment by vyp** [comment]
I see, I agree with the proposal. And I guess `-i` should be short form of `--in-file`. I `old` and `in` file works and wouldn't think it would be confusing.

Should `--changelog` have a form, considering it will probably be commonly used, or would just having a toml field be enough?

**Comment by cburgdorf** [comment]
:+1: sounds good to me!

**Comment by kbknapp** [comment]
Awesome, I'll add this to #64
