### ISSUE TITLE
Docs in the cargo package source

### ISSUE THREAD

**Issue by bluss** [thoughtram/clog#68]
clog 0.8.1 has 17MB of ./docs in their cargo package source. Since this is 17 MB users shouldn't have to download to depend on the package, consider releasing a new clean version.

This is a reminder that cargo includes all non-ignored files in your working directory when you publish — look at `git status` before you publish.

(I downloaded all crates.io crates and I started to grep for junk)

**Comment by kbknapp** [comment]
Thanks for the heads up, I'll add an exclude to the Cargo.toml

:+1:

**Comment by bluss** [comment]
Thanks!
